import localFont from "next/font/local";
import "./globals.css";
import MainNavebar from "@/components/pages/Navebar/mainNavebar";
import MainFooter from "@/components/pages/footer/mainFooter";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// `${geistSans.variable} ${geistMono.variable} antialiased`
export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body
        className={"bg-white dark:bg-slate-950"}
      >
      <MainNavebar/>
        {children}
      <MainFooter/>
      </body>
    </html>
  );
}
